[package]
name = "sys"
version = "0.1.0"
edition = "2021"
license = "WTFPL"
publish = false

[dependencies]
async-recursion = "1.0.0"
async-trait = "0.1.50"
bincode = "1.3.3"
chrono = "0.4"
chrono-humanize = "0.2.1"
clap = "2.33"
console = "0.14.1"
rust_decimal = "1.23"
rust_decimal_macros = "1.23"
fd-lock = "3.0.0"
ftx = { git = "https://github.com/fabianboesiger/ftx", rev = "ce576c74f11c1795eef8cd101735166cb77b7892" }
#ftx = { git = "https://github.com/mvines/ftx", rev = "c9384af98cf34ee5e19bf6a34d8b1f5192b06b5a" }
#ftx = { path = "../ftx" }
itertools = "0.10.0"
separator = "0.4.1"
#pickledb = "0.4"
pickledb = { git = "https://github.com/mvines/pickledb-rs", rev = "af1bfdf5d400b68df9080b29f8b9e9ea57fe035c" }
reqwest = "0.11"
simple_excel_writer = "0.1.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
solana-clap-utils = "=1.10.8"
solana-cli-config = "=1.10.8"
solana-cli-output = "=1.10.8"
solana-client = "=1.10.8"
solana-logger = "=1.10.8"
solana-remote-wallet = "=1.10.8"
solana-sdk = "=1.10.8"
solana-stake-program = "=1.10.8"
solana-transaction-status = "=1.10.8"
solana-vote-program = "=1.10.8"
spl-associated-token-account = "1.0.3"
spl-token = "3.2.0"
spl-token-lending = { git = "https://github.com/solana-labs/solana-program-library.git", rev = "1d1c2b178b8cf2ed3e28006c27b2ba5b3d039d67" }
strum = { version = "0.23", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1", features = ["macros", "time"] }
tokio-binance = "1.0"
tulipv2-sdk-common = "0.9.5"

[profile.dev]
split-debuginfo = "unpacked"
